In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

from src.kmeans import distance

data = load_iris()

In [3]:
X = data['data']
y = data['target']

In [4]:
model = KNeighborsClassifier(n_neighbors=3)

In [5]:
model.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [7]:
X_test = data['data'][:10]
X_test

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [8]:
y_test = data['target'][:10]
y_pred = model.predict(X_test)
model.score(X_test, y_test)

1.0

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [31]:
(X - X_test[:,np.newaxis]).shape

(10, 150, 4)

In [39]:
distances = np.sqrt((X-X_test[:,np.newaxis])**2).sum(axis=2)

In [41]:
nearest_neighbors = np.argsort(distances, axis=1)[:, :5]
nearest_neighbors

array([[ 0, 17,  4, 39, 28],
       [ 1, 34, 45, 12, 25],
       [ 2, 47, 42, 29, 35],
       [ 3, 47, 30, 29, 34],
       [ 4, 37,  0, 17, 40],
       [ 5, 16, 18, 10, 44],
       [ 6, 47,  3,  2, 11],
       [ 7, 39, 49,  0, 26],
       [ 8, 38, 42,  3, 47],
       [ 9, 34,  1, 30, 12]])

In [43]:
top_k_labels = y[nearest_neighbors]
top_k_labels

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
from scipy.stats import mode
mode(top_k_labels,  axis=1)[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])